# Generated by Django 4.2.7 on 2023-11-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedbook',
            name='condition',
            field=models.CharField(choices=[('Like New', 'Like New - as if just purchased new'), ('Slightly Used', 'Slightly Used - some minor wear and tear'), ('Heavily Used', 'Heavily Used - some major wear and tear'), ('Poor', 'Poor - The book is in really bad condition')], max_length=200),
        ),
    ]
