# Generated by Django 4.2.7 on 2023-11-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback'), ('PDF', 'PDF file'), ('Digital', 'Digital file containing the book'), ('Link', 'Link to the book or a free download site'), ('Unknown', 'Book format is unknown (default)')], default='Unknown', max_length=200),
        ),
    ]
