# Generated by Django 4.2.6 on 2023-10-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
