# Generated by Django 4.2.7 on 2023-11-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook_app', '0002_alter_ownedbook_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='due_back',
            field=models.DateField(default=None),
        ),
    ]
